# Generated by Django 4.1.7 on 2023-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Line', models.CharField(max_length=225)),
                ('Date', models.DateField()),
                ('Style', models.CharField(max_length=225)),
                ('Buyer', models.CharField(max_length=225)),
                ('Item', models.CharField(max_length=225)),
                ('OrderQty', models.PositiveIntegerField(default=0)),
                ('In_Put', models.PositiveIntegerField(default=0)),
                ('DailyOutput', models.PositiveIntegerField(default=0)),
                ('BalanceQty', models.FloatField(default=0)),
                ('CMP', models.PositiveIntegerField(default=0)),
                ('DailyCMPbyStyle', models.PositiveIntegerField(default=0)),
                ('Operator', models.PositiveIntegerField(default=0)),
                ('WorkingHr', models.PositiveIntegerField(default=0)),
                ('CMPprHr', models.FloatField(default=0)),
                ('Remark', models.CharField(blank=True, default='abc', max_length=225, null=True)),
            ],
            options={
                'db_table': 'DailyData',
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='id',
            field=models.AutoField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='BuyerName',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemName',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='style',
            name='StyleCode',
            field=models.CharField(max_length=225),
        ),
    ]
