# Generated by Django 4.1.7 on 2023-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dailydata_buyer_id_item_id_style_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='CMP_Hour_Person',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='DailyCMPbyLine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='Helper',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
