# Generated by Django 4.1.7 on 2023-03-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dailydata_cmp_hour_person_dailydata_dailycmpbyline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQty',
            fields=[
                ('line', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=225)),
                ('style', models.CharField(max_length=225)),
                ('Date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OrderQty',
            },
        ),
    ]
