# Generated by Django 4.1.7 on 2023-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_orderqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqty',
            name='order_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
