# Generated by Django 4.1.7 on 2023-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_orderqty_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQtyReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=225)),
                ('buyer', models.CharField(max_length=225)),
                ('style', models.CharField(max_length=225)),
                ('order_qty', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OrderQtyReport',
            },
        ),
    ]
