# Generated by Django 4.1.7 on 2023-03-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderqtyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='StyleCode',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
