# Generated by Django 4.1.7 on 2023-03-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_style_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderqty',
            name='line',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='orderqty',
            name='style',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
