# Generated by Django 4.1.7 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_orderqty_line_alter_orderqty_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqty',
            name='line',
        ),
        migrations.RemoveField(
            model_name='orderqtyreport',
            name='line',
        ),
        migrations.AddField(
            model_name='orderqty',
            name='cmp_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderqtyreport',
            name='cmp_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
