# Generated by Django 4.1.7 on 2023-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_orderqty_cmp_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='CMP',
            field=models.FloatField(default=0.0),
        ),
    ]
