# Generated by Django 4.1.7 on 2023-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_dailydata_cmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='DailyCMPbyLine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='DailyCMPbyStyle',
            field=models.FloatField(default=0),
        ),
    ]
