# Generated by Django 4.1.7 on 2023-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_inputqtyreport_create_at_alter_inputqtyreport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Line', models.CharField(max_length=225)),
                ('Operator', models.PositiveIntegerField(default=0)),
                ('Helper', models.PositiveIntegerField(default=0)),
                ('WorkingHr', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DailyMenPower',
            },
        ),
    ]
