# Generated by Django 4.1.7 on 2023-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_dailymenpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionShit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line', models.CharField(max_length=225)),
                ('style', models.CharField(max_length=225)),
                ('shift_1', models.IntegerField(default=0)),
                ('shift_2', models.IntegerField(default=0)),
                ('shift_3', models.IntegerField(default=0)),
                ('shift_4', models.IntegerField(default=0)),
                ('shift_5', models.IntegerField(default=0)),
                ('shift_6', models.IntegerField(default=0)),
                ('shift_7', models.IntegerField(default=0)),
                ('shift_8', models.IntegerField(default=0)),
                ('shift_9', models.IntegerField(default=0)),
                ('shift_10', models.IntegerField(default=0)),
                ('shift_11', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ProductionShit',
            },
        ),
    ]
