# Generated by Django 4.1.7 on 2023-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_productionshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionshit',
            name='total_output',
            field=models.IntegerField(default=0),
        ),
    ]
