# Generated by Django 4.1.7 on 2023-03-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_productionshit_total_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionshit',
            name='total_hour',
            field=models.IntegerField(default=0),
        ),
    ]
